# Generated by Django 4.2 on 2024-04-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserValidation", "0002_alter_userprofile_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
